language: node_js
node_js:
  - 10
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn docs
before_deploy:
  - cd ..
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-docs.tar.gz ${REPO}/docs
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}/build
deploy:
  provider: releases
  github-token: $GH_API_TOKEN
  file:
    - ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    - ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.docs.tar.gz
  skip_cleanup: true
  on:
    tags: true
