language: node_js
node_js:
  - 10
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn docs
deploy:
  provider: releases
  api_key: $GIHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - build/*
    - docs/*
  skip_cleanup: true
  on:
    tags: true
